image: mcr.microsoft.com/dotnet/core/sdk:latest

stages:
    - build
    - test

build:
    stage: build
    script:
        - "dotnet restore"
        - "dotnet build Arbortrary"
    artifacts:
      paths:
        - Arbortrary/bin/

test:
    stage: test
    script: 
        - "dotnet test"
